source/GNBSys.GerenciaDespesas.UI.Mvc/Controllers/DespesasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GNBSsys.GerenciaDespesas.Infra.Data.Context;
using GNBSys.GerenciaDespesas.Domain.Entities;
using GNBSys.GerenciaDespesas.Application;
using AutoMapper;
using GNBSys.GerenciaDespesas.Application.ViewModels;

namespace GNBSys.GerenciaDespesas.UI.Mvc.Controllers
{
    public class DespesasController : Controller
    {
        private readonly DespesaAppService _despesaAppService;
        private readonly DadosGraficosAppService _dadosGraficosAppService;

        public DespesasController(GerenciaDespesaContext context, IMapper mapper)
        {
            _despesaAppService = new DespesaAppService(context, mapper);
            _dadosGraficosAppService = new DadosGraficosAppService(context);
        }

        public async Task<IActionResult> Index()
        {
            var meses = Task.Run(_despesaAppService.ObterMeses).Result;

            ViewData["Meses"] = new SelectList(meses.OrderBy(x => x.MesId), "MesId", "Nome");
            return View(await _despesaAppService.ObterTodos());
        }
        
        public IActionResult Create()
        {
            var meses = Task.Run(_despesaAppService.ObterMeses).Result;
            var tipoDespesas = Task.Run(_despesaAppService.ObterTipoDepesas).Result;
            ViewData["MesId"] = new SelectList(meses, "MesId", "Nome");
            ViewData["TipoDespesaId"] = new SelectList(tipoDespesas, "TipoDespesaId", "Nome");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DespesaId,TipoDespesaId,MesId,Valor")] DespesaViewModel despesa)
        {
            if (ModelState.IsValid)
            {
                var retorno = await _despesaAppService.Adicionar(despesa);
                if (retorno != null)
                {
                    TempData["Confirmacao"] = " Despesa cadastrada com sucesso!";
                }
                return RedirectToAction(nameof(Index));
            }
            var meses = Task.Run(_despesaAppService.ObterMeses).Result;
            var tipoDespesas = Task.Run(_despesaAppService.ObterTipoDepesas).Result;
            ViewData["MesId"] = new SelectList(meses, "MesId", "Nome");
            ViewData["TipoDespesaId"] = new SelectList(tipoDespesas, "TipoDespesaId", "Nome");
            return View(despesa);
        }

        // GET: Despesas/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var despesa = await _despesaAppService.ObterPorId(id);
            if (despesa == null)
            {
                return NotFound();
            }
            var meses = Task.Run(_despesaAppService.ObterMeses).Result;
            var tipoDespesas = Task.Run(_despesaAppService.ObterTipoDepesas).Result;
            ViewData["MesId"] = new SelectList(meses, "MesId", "Nome");
            ViewData["TipoDespesaId"] = new SelectList(tipoDespesas, "TipoDespesaId", "Nome");
            return View(despesa);
        }

        // POST: Despesas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("DespesaId,TipoDespesaId,MesId,Valor")] DespesaViewModel despesa)
        {
            if (id != despesa.DespesaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var retorno = await _despesaAppService.Atualizar(despesa);

                    if (retorno != null)
                    {
                        TempData["Confirmacao"] = " Despesa atualizada com sucesso!";
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    var exits = await DespesaExists(despesa.DespesaId);

                    if (!exits)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            var meses = Task.Run(_despesaAppService.ObterMeses).Result;
            var tipoDespesas = Task.Run(_despesaAppService.ObterTipoDepesas).Result;
            ViewData["MesId"] = new SelectList(meses, "MesId", "Nome");
            ViewData["TipoDespesaId"] = new SelectList(tipoDespesas, "TipoDespesaId", "Nome");
            return View(despesa);
        }

        // POST: Despesas/Delete/5
        [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Guid id)
        {

            await _despesaAppService.RemoverAsync(id);

            TempData["Confirmacao"] = " Despesa excluída com sucesso!";

            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> DespesaExists(Guid id)
        {
            var depesaExists = await _despesaAppService.ObterPorId(id);
            if (depesaExists.DespesaId != null)
                return true;

            return false;
        }

        public JsonResult GastosTotaisMes(int ordem)
        {
            GastosTotaisMesViewModel gastos = new GastosTotaisMesViewModel();
            gastos = _despesaAppService.RetornarDadosGastosTotaisMes(ordem);
            //gastos.ValorTotalGasto = _context.TDespesa.Where(x => x.Mes.Ordem == ordem).Sum(x => x.Valor);
            //gastos.Salario = _context.TSalario.Where(x => x.Mes.Ordem == ordem).Select(x => x.Valor).FirstOrDefault();

            return Json(gastos);

        }

        //Graficos Donut
        public JsonResult GastosMes(int ordem)
        {
            var dados = _dadosGraficosAppService.RetornarDadosGastosMes(ordem);
            return Json(dados);
        }

        //Grafico de Linha
        public JsonResult GastosTotais()
        {
            var dados = _dadosGraficosAppService.RetornarDadosGraficoGastosTotais();
            return Json(dados);
        }
    }
}

source/GNBSys.GerenciaDespesas.UI.Mvc/Controllers/SalariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GNBSsys.GerenciaDespesas.Infra.Data.Context;
using GNBSys.GerenciaDespesas.Domain.Entities;
using GNBSys.GerenciaDespesas.Application;
using AutoMapper;
using GNBSys.GerenciaDespesas.Application.ViewModels;

namespace GNBSys.GerenciaDespesas.UI.Mvc.Controllers
{
    public class SalariosController : Controller
    {
        //private readonly GerenciaDespesaContext _context;
        private readonly SalarioAppService _salarioAppService;
        //private readonly IMapper _mapper;

        public SalariosController(GerenciaDespesaContext context, IMapper mapper)
        {
            _salarioAppService = new SalarioAppService(context, mapper);
        }

        // GET: Salarios
        public async Task<IActionResult> Index()
        {
            //var gerenciaDespesaContext = _context.TSalario.Include(s => s.Mes);
            return View(await _salarioAppService.ObterTodos());
        }

        // GET: Salarios/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var salario = await _context.TSalario
            //    .Include(s => s.Mes)
            //    .FirstOrDefaultAsync(m => m.SalarioId == id);
            var salario = await _salarioAppService.ObterPorId(id);
            if (salario == null)
            {
                return NotFound();
            }

            return View(salario);
        }

        // GET: Salarios/Create
        public IActionResult Create()
        {
            var meses = Task.Run(_salarioAppService.ObterMeses).Result;
            ViewData["MesId"] = new SelectList(meses, "MesId", "Nome");
            return View();
        }

        // POST: Salarios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SalarioId,Valor,MesId")] SalarioViewModel salario)
        {
            if (ModelState.IsValid)
            {
                //salario.SalarioId = Guid.NewGuid();
                await _salarioAppService.Adicionar(salario);
                TempData["Confirmacao"] = "Salário cadastrado com sucesso";
                return RedirectToAction(nameof(Index));
            }
            var meses = Task.Run(_salarioAppService.ObterMeses).Result;
            ViewData["MesId"] = new SelectList(meses, "MesId", "Nome");
            return View(salario);
        }

        // GET: Salarios/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var salario = await _salarioAppService.ObterPorId(id);
            if (salario == null)
            {
                return NotFound();
            }
            var meses = Task.Run(_salarioAppService.ObterMeses).Result;
            ViewData["MesId"] = new SelectList(meses, "MesId", "Nome");

            return View(salario);
        }

        // POST: Salarios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("SalarioId,Valor,MesId")] SalarioViewModel salario)
        {
            if (id != salario.SalarioId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                SalarioViewModel retorno;

                try
                {
                    retorno = await _salarioAppService.Atualizar(salario);
                }
                catch (DbUpdateConcurrencyException)
                {
                    var exits = await SalarioExists(salario.SalarioId);

                    if (!exits)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                if(retorno != null)
                {
                    TempData["Confirmacao"] = "O salário foi atualizado com sucesso!";
                }

                return RedirectToAction(nameof(Index));
            }

            var meses = Task.Run(_salarioAppService.ObterMeses).Result;
            ViewData["MesId"] = new SelectList(meses, "MesId", "Nome");
            return View(salario);
        }

        //// GET: Salarios/Delete/5
        //public async Task<IActionResult> Delete(Guid? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var salario = await _context.TSalario
        //        .Include(s => s.Mes)
        //        .FirstOrDefaultAsync(m => m.SalarioId == id);
        //    if (salario == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(salario);
        //}

        // POST: Salarios/Delete/5
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> Delete(Guid id)
        {
            await _salarioAppService.RemoverAsync(id);
            TempData["Confirmacao"] = "O salário foi excluído com sucesso!";
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> SalarioExists(Guid id)
        {
            var salarioExists = await _salarioAppService.ObterPorId(id);
            if (salarioExists.SalarioId != null)
                return true;

            return false;
        }
    }
}

source/GNBSys.GerenciaDespesas.UI.Mvc/Controllers/TiposAtivosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GNBSsys.GerenciaDespesas.Infra.Data.Context;
using GNBSys.GerenciaDespesas.Domain.Entities.Receita;

namespace GNBSys.GerenciaDespesas.UI.Mvc.Controllers
{
    public class TiposAtivosController : Controller
    {
        private readonly GerenciaDespesaContext _context;

        public TiposAtivosController(GerenciaDespesaContext context)
        {
            _context = context;
        }

        // GET: TiposAtivos
        public async Task<IActionResult> Index()
        {
            return View(await _context.TTipoAtivo.ToListAsync());
        }

        // GET: TiposAtivos/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tipoAtivo = await _context.TTipoAtivo
                .FirstOrDefaultAsync(m => m.TipoAtivoId == id);
            if (tipoAtivo == null)
            {
                return NotFound();
            }

            return View(tipoAtivo);
        }

        // GET: TiposAtivos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TiposAtivos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TipoAtivoId,Nome")] TipoAtivo tipoAtivo)
        {
            if (ModelState.IsValid)
            {
                tipoAtivo.TipoAtivoId = Guid.NewGuid();
                _context.Add(tipoAtivo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tipoAtivo);
        }

        // GET: TiposAtivos/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tipoAtivo = await _context.TTipoAtivo.FindAsync(id);
            if (tipoAtivo == null)
            {
                return NotFound();
            }
            return View(tipoAtivo);
        }

        // POST: TiposAtivos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("TipoAtivoId,Nome")] TipoAtivo tipoAtivo)
        {
            if (id != tipoAtivo.TipoAtivoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tipoAtivo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TipoAtivoExists(tipoAtivo.TipoAtivoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tipoAtivo);
        }

        // GET: TiposAtivos/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tipoAtivo = await _context.TTipoAtivo
                .FirstOrDefaultAsync(m => m.TipoAtivoId == id);
            if (tipoAtivo == null)
            {
                return NotFound();
            }

            return View(tipoAtivo);
        }

        // POST: TiposAtivos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var tipoAtivo = await _context.TTipoAtivo.FindAsync(id);
            _context.TTipoAtivo.Remove(tipoAtivo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TipoAtivoExists(Guid id)
        {
            return _context.TTipoAtivo.Any(e => e.TipoAtivoId == id);
        }
    }
}

source/GNBSys.GerenciaDespesas.UI.Mvc/Views/Shared/_GastoMes.cshtml
<div class="graficoGastosMes">
    <canvas id="graficoGastosMes" style="width:300px; height:300px"></canvas>
</div>

source/GNBSys.GerenciaDespesas.UI.Mvc/Views/Shared/_GastoTotalMes.cshtml
<div class="GraficoGastoTotalMes">
    <canvas id="GraficoGastoTotalMes" style="width:300px; height:300px"></canvas>
</div>

source/GNBSys.GerenciaDespesas.UI.Mvc/Views/Shared/_GastosTotais.cshtml
<canvas id="GraficoGastosTotais"></canvas>

source/GNBSys.GerenciaDespesas.UI.Mvc/Views/Shared/_Layout - Cópia.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GNBSys.GerenciaDespesas</title>

    <environment include="Development">
        @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />*@
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" />
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
        
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" />
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GNBSys.GerenciaDespesas</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>                
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Despesas" asp-action="Index">Despesas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoDespesas" asp-action="Index">Tipo Despesas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Salarios" asp-action="Index">Salarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoMovimentacoesCarteira" asp-action="Index">Tipo Movimentações Carteira</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TiposAtivos" asp-action="Index">Tipos Ativos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - GNBSys.GerenciaDespesas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    @*<environment include="Development">
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>
        </environment>*@
    <environment include="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>
        <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>

    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>
        <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>

    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    
</body>
</html>

source/GNBSys.GerenciaDespesas.UI.Mvc/Views/Shared/_MainMenu.cshtml
<ul class="sidebar-menu" data-widget="tree">
    <li class="header">Cabeçalho</li>
    <!-- Optionally, you can add icons to the links -->

    <li class="active"><a asp-area="" asp-controller="Home" asp-action="Index"> <i class="fa fa-home"></i>Inicio</a></li>
    @*<li><a href="#"><i class="fa fa-link"></i> <span>Outro Link</span></a></li>*@
    <li class="treeview">
        <a href="#">
            <i class="fa fa-edit"></i> <span>Despesas</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu">
            <li class="nav-item">
                <a asp-area="" asp-controller="Despesas" asp-action="Index"><i class="fa fa-circle-o"></i>Despesas</a>
            </li>
            <li class="nav-item">
                <a asp-area="" asp-controller="TipoDespesas" asp-action="Index"><i class="fa fa-circle-o"></i>Tipo Despesas</a>
            </li>
            <li class="nav-item">
                <a asp-area="" asp-controller="Salarios" asp-action="Index"><i class="fa fa-circle-o"></i>Salarios</a>
            </li>
        </ul>
    </li>
    <li class="treeview">
        <a href="#">
            <i class="fa fa-money"></i> <span>Receitas</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu">
            <li class="nav-item">
                <a asp-area="" asp-controller="TiposAtivos" asp-action="Index"><i class="fa fa-circle-o"></i>Tipos Ativos</a>
            </li>
            <li class="nav-item">
                <a asp-area="" asp-controller="TipoMovimentacoesCarteira" asp-action="Index"><i class="fa fa-circle-o"></i>Tipo Movimentações Carteira</a>
            </li>
        </ul>
    </li>
</ul>