source/GNBSys.GerenciaDespesas.UI.Mvc/Controllers/DespesasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GNBSsys.GerenciaDespesas.Infra.Data.Context;
using GNBSys.GerenciaDespesas.Domain.Entities;
using GNBSys.GerenciaDespesas.Application;
using AutoMapper;
using GNBSys.GerenciaDespesas.Application.ViewModels;

namespace GNBSys.GerenciaDespesas.UI.Mvc.Controllers
{
    public class DespesasController : Controller
    {
        private readonly DespesaAppService _despesaAppService;
        private readonly DadosGraficosAppService _dadosGraficosAppService;

        public DespesasController(GerenciaDespesaContext context, IMapper mapper)
        {
            _despesaAppService = new DespesaAppService(context, mapper);
            _dadosGraficosAppService = new DadosGraficosAppService(context);
        }

        public async Task<IActionResult> Index()
        {
            var meses = Task.Run(_despesaAppService.ObterMeses).Result;

            ViewData["Meses"] = new SelectList(meses.OrderBy(x => x.MesId), "MesId", "Nome");
            return View(await _despesaAppService.ObterTodos());
        }
        
        public IActionResult Create()
        {
            var meses = Task.Run(_despesaAppService.ObterMeses).Result;
            var tipoDespesas = Task.Run(_despesaAppService.ObterTipoDepesas).Result;
            ViewData["MesId"] = new SelectList(meses, "MesId", "Nome");
            ViewData["TipoDespesaId"] = new SelectList(tipoDespesas, "TipoDespesaId", "Nome");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DespesaId,TipoDespesaId,MesId,Valor")] DespesaViewModel despesa)
        {
            if (ModelState.IsValid)
            {
                var retorno = await _despesaAppService.Adicionar(despesa);
                if (retorno != null)
                {
                    TempData["Confirmacao"] = " Despesa cadastrada com sucesso!";
                }
                return RedirectToAction(nameof(Index));
            }
            var meses = Task.Run(_despesaAppService.ObterMeses).Result;
            var tipoDespesas = Task.Run(_despesaAppService.ObterTipoDepesas).Result;
            ViewData["MesId"] = new SelectList(meses, "MesId", "Nome");
            ViewData["TipoDespesaId"] = new SelectList(tipoDespesas, "TipoDespesaId", "Nome");
            return View(despesa);
        }

        // GET: Despesas/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var despesa = await _despesaAppService.ObterPorId(id);
            if (despesa == null)
            {
                return NotFound();
            }
            var meses = Task.Run(_despesaAppService.ObterMeses).Result;
            var tipoDespesas = Task.Run(_despesaAppService.ObterTipoDepesas).Result;
            ViewData["MesId"] = new SelectList(meses, "MesId", "Nome");
            ViewData["TipoDespesaId"] = new SelectList(tipoDespesas, "TipoDespesaId", "Nome");
            return View(despesa);
        }

        // POST: Despesas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("DespesaId,TipoDespesaId,MesId,Valor")] DespesaViewModel despesa)
        {
            if (id != despesa.DespesaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var retorno = await _despesaAppService.Atualizar(despesa);

                    if (retorno != null)
                    {
                        TempData["Confirmacao"] = " Despesa atualizada com sucesso!";
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    var exits = await DespesaExists(despesa.DespesaId);

                    if (!exits)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            var meses = Task.Run(_despesaAppService.ObterMeses).Result;
            var tipoDespesas = Task.Run(_despesaAppService.ObterTipoDepesas).Result;
            ViewData["MesId"] = new SelectList(meses, "MesId", "Nome");
            ViewData["TipoDespesaId"] = new SelectList(tipoDespesas, "TipoDespesaId", "Nome");
            return View(despesa);
        }

        // POST: Despesas/Delete/5
        [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Guid id)
        {

            await _despesaAppService.RemoverAsync(id);

            TempData["Confirmacao"] = " Despesa excluída com sucesso!";

            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> DespesaExists(Guid id)
        {
            var depesaExists = await _despesaAppService.ObterPorId(id);
            if (depesaExists.DespesaId != null)
                return true;

            return false;
        }

        public JsonResult GastosTotaisMes(int ordem)
        {
            GastosTotaisMesViewModel gastos = new GastosTotaisMesViewModel();
            gastos = _despesaAppService.RetornarDadosGastosTotaisMes(ordem);
            //gastos.ValorTotalGasto = _context.TDespesa.Where(x => x.Mes.Ordem == ordem).Sum(x => x.Valor);
            //gastos.Salario = _context.TSalario.Where(x => x.Mes.Ordem == ordem).Select(x => x.Valor).FirstOrDefault();

            return Json(gastos);

        }

        //Graficos Donut
        public JsonResult GastosMes(int ordem)
        {
            var dados = _dadosGraficosAppService.RetornarDadosGastosMes(ordem);
            return Json(dados);
        }

        //Grafico de Linha
        public JsonResult GastosTotais()
        {
            var dados = _dadosGraficosAppService.RetornarDadosGraficoGastosTotais();
            return Json(dados);
        }
    }
}

source/GNBSys.GerenciaDespesas.UI.Mvc/ViewComponents/EstatisticasViewComponent.cs
using AutoMapper;
using GNBSsys.GerenciaDespesas.Infra.Data.Context;
using GNBSys.GerenciaDespesas.Application;
using GNBSys.GerenciaDespesas.Application.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GNBSys.GerenciaDespesas.UI.Mvc.ViewComponents
{
    public class EstatisticasViewComponent : ViewComponent
    {
        private readonly GerenciaDespesaContext _ctx;
        private readonly DespesaAppService _despesaAppService;

        public EstatisticasViewComponent(GerenciaDespesaContext ctx, IMapper mapper)
        {
            _ctx = ctx;
            _despesaAppService = new DespesaAppService(ctx, mapper);
        }

        public IViewComponentResult Invoke()
        {
            EstatisticasDespesasViewModel estatisticas = new EstatisticasDespesasViewModel();
            estatisticas = _despesaAppService.RetornarDadosEstatisticasDespesas();
            return View(estatisticas);
        }
    }
}

source/GNBSys.GerenciaDespesas.UI.Mvc/Views/Despesas/Create.cshtml
@model GNBSys.GerenciaDespesas.Application.ViewModels.DespesaViewModel

@{
    ViewData["Title"] = "Create";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Despesas
        <small>Nova Despesa</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Despesas</a></li>
        <li class="active">Cadastro nova Despesa</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <!-- left column -->
        <div class="col-md-8">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Cadastro</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form asp-action="Create" class="form border rounded">
                    <div class="box-body">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label class="control-label">Tipo de Despesa</label>
                            <div class="input-group">
                                <select asp-for="TipoDespesaId" class="form-control" asp-items="ViewBag.TipoDespesaId"></select>
                                <div class="input-group-append">
                                    <button type="button" class="btn btn-info" data-toggle="tooltip"
                                            data-placement="right" title="Adicionar novo tipo de despesa" onclick="MostrarModal()">
                                        <i class="far fa-plus-square"></i>
                                    </button>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label">Mês</label>
                            <select asp-for="MesId" class="form-control" asp-items="ViewBag.MesId"></select>
                        </div>
                        <div class="form-group">
                            <label asp-for="Valor" class="control-label"></label>
                            <input asp-for="Valor" class="form-control" />
                            <span asp-validation-for="Valor" class="text-danger"></span>
                        </div>                        
                        <div class="box-footer">
                            <input type="submit" value="Salvar" class="btn btn-primary" />&nbsp;&nbsp;
                            <a asp-action="Index" class="btn btn-default">Voltar</a>
                        </div>
                    </div>
                </form>
            </div>

        </div>
        <!-- /.box -->

    </div>
    <!--/.col (left) -->
    <!-- /.row -->
</section>

<div class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Adicionar Nova Despesa</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input class="form-control txtDespesa" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary btnAdicionar">Adicionar</button>
                <button type="button" class="btn btn--danger" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });

        function MostrarModal() {
            $('.modal').modal();

            $('.btnAdicionar').on('click', function () {
                var txtDespesa = $('.txtDespesa').val();

                $.ajax({
                    url: "/TipoDespesas/AdicionarTipoDespesa",
                    method: "POST",
                    data: { txtDespesa: txtDespesa },
                    success: function (data) {
                        if (!data) {
                            $('.modal').modal('hide');
                            $('.modal').modal('dispose');
                            $('.btnAdicionar').unbind('click');
                            $('.txtDespesa').val('');
                            alert("Tipo de despesa já cadastrada.");
                        } else {
                            location.reload(true);
                        }
                    }
                });
            });
        }

    </script>
}

source/GNBSys.GerenciaDespesas.UI.Mvc/Views/Despesas/Edit.cshtml
@model GNBSys.GerenciaDespesas.Application.ViewModels.DespesaViewModel

@{
    ViewData["Title"] = "Edit";
}

<div class="formulario">

    <h4>Atualizar despesa</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit" class="form border rounded">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="DespesaId" />
                <div class="form-group">
                    <label class="control-label">Tipo de Despesa</label>
                    <select asp-for="TipoDespesaId" class="form-control" asp-items="ViewBag.TipoDespesaId"></select>
                    <span asp-validation-for="TipoDespesaId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">Mês</label>
                    <select asp-for="MesId" class="form-control" asp-items="ViewBag.MesId"></select>
                    <span asp-validation-for="MesId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Valor" class="control-label"></label>
                    <input asp-for="Valor" class="form-control" />
                    <span asp-validation-for="Valor" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Salvar" class="btn btn-outline-success btn-sm" />&nbsp;&nbsp;
                    <a asp-action="Index" class="btn btn-outline-dark btn-sm">Voltar</a>
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

source/GNBSys.GerenciaDespesas.UI.Mvc/Views/Despesas/Index.cshtml
@model IEnumerable<GNBSys.GerenciaDespesas.Application.ViewModels.DespesaViewModel>

@{
    ViewData["Title"] = "Index";
}
<link rel="stylesheet" href="../../bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
<section class="content-header">
    <h1>
        Despesas
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Despesas</a></li>
        @*<li><a href="#">Charts</a></li>*@
        <li class="active">Despesas</li>
    </ol>
</section>

<section class="content">

    <div class="row">
        <div class="col-md-10">
            <h4>Despesas Cadastrados</h4>
        </div>
        <div class="col-md-2 pull-right">
            <p>
                <a class="btn btn-primary btn-sm" asp-action="Create">Nova Despesa</a>
            </p>
        </div>

    </div>
    @if (TempData["Confirmacao"] != null)
    {
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-check"></i> Alerta!</h4>
            @TempData["Confirmacao"]
        </div>
    }


    <div class="box box-default" data-select2-id="14">
        <div class="box-header with-border">
            <h3 class="box-title">Mês Seleção dos Gráficos</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body" data-select2-id="13">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="col-form-label">Selecione o Mês para respectiva apresentação dos gráficos:</label>

                        <div class="form-group row">

                            <div class="col-sm-9">
                                <select class="form-control select2 select2-hidden-accessible escolhaMes"
                                        style="width: 100%;" tabindex="-1" aria-hidden="true" asp-items="ViewBag.Meses"></select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <!-- DONUT CHART -->
            <div class="box box-danger">
                <div class="box-header with-border">
                    <h3 class="box-title">Donut Chart</h3>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                    </div>
                </div>
                <div class="box-body">
                    <canvas id="pieChart" style="height:250px"></canvas>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
            @*<partial name="_GastoTotalMes" />*@
        </div>
        <div class="col-md-6">
            <!-- DONUT CHART -->
            <div class="box box-danger">
                <div class="box-header with-border">
                    <h3 class="box-title">Donut Chart</h3>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                    </div>
                </div>
                <div class="box-body">
                    <canvas id="pieChart" style="height:250px"></canvas>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
            @*<partial name="_GastoMes" />*@
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <!-- AREA CHART -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Area Chart</h3>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                    </div>
                </div>
                <div class="box-body">
                    <div class="chart">
                        <canvas id="areaChart" style="height:250px"></canvas>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
            <partial name="_GastosTotais" />
        </div>
        <div class="estatisticas col-md-6">
            <div class="alert alert-info">
                @await Component.InvokeAsync("Estatisticas")
            </div>
        </div>
    </div>
</section>

<section class="content">
    @if (TempData["Confirmacao"] != null)
    {
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-check"></i> Alerta!</h4>
            @TempData["Confirmacao"]
        </div>
    }
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <div class="row">
                        <div class="col-md-10">
                            <h3 class="box-title">Salários Cadastrados</h3>
                        </div>
                        <div class="col-md-2">
                            <p class="btnNovo">
                                <a class="btn btn-block btn-primary btn-sm" asp-action="Create">Nova Despesa</a>
                            </p>
                        </div>
                    </div>
                </div>

                <!-- /.box-header -->
                <div class="box-body">
                    <table id="tabelaDespesas" class="table table-bordered table-striped table-sm">
                        <thead>
                            <tr>
                                <th>
                                    Mês
                                </th>
                                <th>
                                    Tipo de Despesa
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Valor)
                                </th>
                                <th>Opções</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Mes.Nome)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.TipoDespesa.Nome)
                                    </td>

                                    <td>
                                        @Html.DisplayFor(modelItem => item.Valor)
                                    </td>
                                    <td>
                                        <a asp-action="Edit" asp-route-id="@item.DespesaId" class="btn btn-info btn-sm">Atualizar</a> |
                                        <a onclick="ExibirModal('@item.DespesaId')" class="btn btn-danger btn-sm">Excluir</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>
                                    Mês
                                </th>
                                <th>
                                    Tipo de Despesa
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Valor)
                                </th>
                                <th>Opções</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>



@*<table id="tabelaDespesas" class="table table-sm">
        <thead>
            <tr>
                <th>
                    Mês
                </th>
                <th>
                    Tipo de Despesa
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Valor)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>

                    <td>
                        @Html.DisplayFor(modelItem => item.Mes.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TipoDespesa.Nome)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Valor)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.DespesaId" class="btn btn-outline-info btn-sm">Atualizar</a> |
                        <a onclick="ExibirModal('@item.DespesaId')" class="btn btn-outline-danger btn-sm">Excluir</a>

                    </td>
                </tr>
            }
        </tbody>
    </table>*@
    </div>
    </div>

<div class="modal modal-danger fade" id="modal-danger">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Excluir</h4>
            </div>
            <div class="modal-body">
                <p>Deseja prosseguir com a exclusão desta despesa?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Não</button>
                <button type="button" class="btn btn-outline btnExcluir">Sim</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->
@*<div class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Excluir</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Deseja prosseguir com a exclusão desta despesa?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-primary btnExcluir">Sim</button>
                    <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Não</button>
                </div>
            </div>
        </div>
    </div>*@

@section Scripts{

    @*<script src="~/js/GraficoTotalMesDonut.js"></script>
        <script src="~/js/MetodosGerais.js"></script>
        <script src="~/js/GraficoGastoMesDonut.js"></script>
        <script src="~/js/GraficoGastosTotaisLine.js"></script>*@

    <script src="~/dist/js/pages/dashboard.js"></script>

    <script>

        $(document).ready(function () {
            var mes = new Date().getMonth() + 1;
            $('.escolhaMes').val(parseInt(mes)).change();
        });


        $('#tabelaDespesas').DataTable({
            'paging': true,
            'lengthChange': true,
            'searching': true,
            'ordering': true,
            'info': true,
            'autoWidth': true
        })

        //CarregarDadosGastosTotais();
        //CarregarDadosMes(); DESCOMENTAR A PARTIR DAQUI PARA EXIBIR OS GRAFICOS
        //CarregarDadosGastosTotaisMes();
        //CarregarDadosGastosTotais();

        function ExibirModal(id) {
            $('.modal').modal();
            $('.btnExcluir').on('click', function () {
                $.ajax({
                    type: 'POST',
                    url: 'Despesas/Delete',
                    data: { id: id },
                    success: function () {
                        $('.modal').modal('hide');
                        location.reload(true);
                    }
                });
            });
        }
    </script>
}